on: push
name: CI
jobs:
  ci:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node: ['10', '9', '8']
    name: run on Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm test
